environment:
    matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: wlp
          RUNTIME_VERSION: 19.0.0.9
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: wlp
          RUNTIME_VERSION: 19.0.0.6
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: ol
          RUNTIME_VERSION: 19.0.0.9
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: ol
          RUNTIME_VERSION: 19.0.0.6

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn

before_build:
    - cmd: |
        echo "Installing ci.common lib ...."
        git clone https://github.com/OpenLiberty/ci.common.git ci.common
        cd ci.common
        mvn clean install
        cd..
#        echo "Installing ci.ant lib ...."
#        git clone https://github.com/OpenLiberty/ci.ant.git ci.ant
#        cd ci.ant
#        mvn clean install
#        cd..

build_script:
    - cmd: |
        gradlew.bat clean install check -Ptest.exclude="**/*15*","**/*LibertyTest*","**/*OldLibertyTest*","**/*LibertyMultiServerTest*" -Druntime=%RUNTIME% -DruntimeVersion=%RUNTIME_VERSION% --stacktrace --info --no-daemon
        gradlew.bat wrapper --gradle-version 4.10
        gradlew.bat clean install check -Ptest.include="**/*15*" -Druntime=%RUNTIME% -DruntimeVersion=%RUNTIME_VERSION% --stacktrace --info --no-daemon

test: off
