environment:
    matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: wlp
          RUNTIME_VERSION: 18.0.0.4
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: wlp
          RUNTIME_VERSION: 19.0.0.1
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: ol
          RUNTIME_VERSION: 18.0.0.4
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME: ol
          RUNTIME_VERSION: 19.0.0.1

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn

before_build:
    - cmd: |
        echo "Installing ci.common lib ...."
        git clone https://github.com/wasdev/ci.common.git ci.common
        cd ci.common
        mvn clean install
        cd..

build_script:
  # Build the compiled extension
  - "gradlew.bat install integrationTest -Druntime=%RUNTIME% -DruntimeVersion=%RUNTIME_VERSION% --stacktrace --info --no-daemon"

test: off
